name: Deploy Smart Contracts
on: [push]
jobs:
  DeploySmartContracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          repository: ${{ github.repository }}
      - name: Mythril code check
        run: |-
          # TODO: fix assertion issue
          pip3 install mythril
          myth analyze contracts/Adoption.sol || true
      - name: Run unit tests
        run: |- 
          npm install
          npx ganache -p 8545 > /dev/null &
          npx truffle migrate --network development
          npx truffle test --network development
          kill $(lsof -t -i:8545)
      - name: Deploy to Goerli testnet
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}  
          MNEMONIC: ${{ secrets.MNEMONIC }}
        run: |-
          npx truffle migrate --network staging