name: Deploy Smart Contracts
on: [push]
jobs:
  DeploySmartContracts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
          repository: ${{ github.repository }}
      - name: Mythril code check
        run: |-
          # TODO: fix assertion issue
          pip3 install mythril
          myth analyze contracts/Adoption.sol || true
      - name: deploy
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}  
          MNEMONIC: ${{ secrets.MNEMONIC }}
        run: |-
          npm install
          npx truffle migrate --network staging